#!/bin/bash

export cap_operations="MonoAsKernelLift EpiAsCokernelColift IdentityMorphism Inverse Kernel KernelEmb KernelEmbWithGivenKernel KernelLift KernelLiftWithGivenKernel Cokernel CokernelProj CokernelProjWithGive\
nCokernel CokernelColift CokernelColiftWithGivenCokernel PreCompose PostCompose ZeroObject ZeroMorphism DirectSum TerminalObject UniversalMorphismIntoTerminalObject UniversalMorphismI\
ntoTerminalObjectWithGivenTerminalObject InitialObject UniversalMorphismFromInitialObject UniversalMorphismFromInitialObjectWithGivenInitialObject DirectProduct ProjectionInFactorOfDi\
rectProduct ProjectionInFactorOfDirectProductWithGivenDirectProduct UniversalMorphismIntoDirectProduct UniversalMorphismIntoDirectProductWithGivenDirectProduct IsEqualForMorphisms IsZ\
eroForMorphisms AdditionForMorphisms AdditiveInverseForMorphisms Coproduct InjectionOfCofactorOfCoproduct InjectionOfCofactorOfCoproductWithGivenCoproduct UniversalMorphismFromCoprodu\
ct UniversalMorphismFromCoproductWithGivenCoproduct EqualityOfSubobjects EqualityOfFactorobjects Dominates Codominates Pullback ProjectionInFactorOfPullback ProjectionInFactorOfPullba\
ckWithGivenPullback UniversalMorphismIntoPullback UniversalMorphismIntoPullbackWithGivenPullback Pushout InjectionOfCofactorOfPushout InjectionOfCofactorOfPushoutWithGivenPushout Univ\
ersalMorphismFromPushout UniversalMorphismFromPushoutWithGivenPushout Image ImageEmbedding ImageEmbeddingWithGivenImage IsWellDefinedForMorphisms IsWellDefinedForObjects IsZeroForObje\
cts IsMonomorphism IsEpimorphism IsIsomorphism EpiMonoFactorization CoastrictionToImage CoastrictionToImageWithGivenImage UniversalMorphismFromImage UniversalMorphismFromImageWithGive\
nImage DomainAssociatedMorphismCodomainTriple Domain Codomain AssociatedMorphism PseudoInverse KernelObjectFunctorial CokernelFunctorial TerminalObjectFunctorial InitialObjectFunctori\
al DirectProductFunctorial CoproductFunctorial DirectSumFunctorial PullbackFunctorial PushoutFunctorial GeneralizedMorphismFromFactorToSubobject HorizontalPreCompose VerticalPreCompos\
e IdentityTwoCell HonestRepresentative IsWellDefinedForTwoCells"

for i in $cap_operations; do 
CAPSTR="$(git grep $i"Op" | cat)"
if [[ $CAPSTR = gap* ]]; then echo $i"Op"; fi;
done
