codecov:
  disable_default_path_fixes: true
  require_ci_to_pass: false
comment:
  after_n_builds: 20
flags:
  CAP:
    paths:
      - "CAP/"
  ActionsForCAP:
    paths:
      - "ActionsForCAP/"
  AdditiveClosuresForCAP:
    paths:
      - "AdditiveClosuresForCAP/"
  AttributeCategoryForCAP:
    paths:
      - "AttributeCategoryForCAP/"
  CartesianCategories:
    paths:
      - "CartesianCategories/"
  CompilerForCAP:
    paths:
      - "CompilerForCAP/"
  ComplexesAndFilteredObjectsForCAP:
    paths:
      - "ComplexesAndFilteredObjectsForCAP/"
  FreydCategoriesForCAP:
    paths:
      - "FreydCategoriesForCAP/"
  GeneralizedMorphismsForCAP:
    paths:
      - "GeneralizedMorphismsForCAP/"
  GradedModulePresentationsForCAP:
    paths:
      - "GradedModulePresentationsForCAP/"
  GroupRepresentationsForCAP:
    paths:
      - "GroupRepresentationsForCAP/"
  GroupsAsCategoriesForCAP:
    paths:
      - "GroupsAsCategoriesForCAP/"
  HomologicalAlgebraForCAP:
    paths:
      - "HomologicalAlgebraForCAP/"
  InternalExteriorAlgebraForCAP:
    paths:
      - "InternalExteriorAlgebraForCAP/"
  LinearAlgebraForCAP:
    paths:
      - "LinearAlgebraForCAP/"
  LinearClosuresForCAP:
    paths:
      - "LinearClosuresForCAP/"
  ModulePresentationsForCAP:
    paths:
      - "ModulePresentationsForCAP/"
  ModulesOverLocalRingsForCAP:
    paths:
      - "ModulesOverLocalRingsForCAP/"
  MonoidalCategories:
    paths:
      - "MonoidalCategories/"
  ToricSheaves:
    paths:
      - "ToricSheaves/"
