#!/usr/bin/env python3
"""
Match AutoDoc-generated .tst files back to their source example .g files,
print the mappings, and insert a '# extracted from <path>' comment into each
test file immediately after the START_TEST line.

Usage:
    python3 match_tst_to_examples.py           # all packages
    python3 match_tst_to_examples.py <pkg>     # single package

<pkg> can be a package name (e.g. "FpCategories") or a path to a package
directory (e.g. "." when running from inside the package directory via make).
The monorepo root is always inferred from the location of this script.
"""

import sys
from pathlib import Path


def get_tst_input_lines(tst_path: Path) -> list[str]:
    """Extract GAP input lines from a .tst file, stripping 'gap> ' / '> ' prefixes."""
    lines = []
    with open(tst_path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if line.startswith("gap> "):
                lines.append(line[5:])
            elif line.startswith("> "):
                lines.append(line[2:])
    return lines


def get_example_code_lines(g_path: Path) -> list[str]:
    """Extract actual code lines from an example .g file.

    Lines starting with '#!' are AutoDoc directives or expected output; they
    are excluded.  Everything else (including blank lines and GAP comments
    like '# remark') is kept so that it can be matched against the test file.
    Non-blank lines only are returned for the similarity score.
    """
    lines = []
    with open(g_path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if line.startswith("#!"):
                continue
            if line.strip():          # skip truly blank lines
                lines.append(line)
    return lines


def similarity(tst_lines: list[str], example_lines: list[str]) -> float:
    """Fraction of example code lines that appear in the tst input line set."""
    if not example_lines:
        return 0.0
    tst_set = set(tst_lines)
    matches = sum(1 for l in example_lines if l in tst_set)
    return matches / len(example_lines)


def find_example_files(package_dir: Path) -> list[Path]:
    """Return all .g and .gi files under <package>/examples/ (recursively)."""
    examples_dir = package_dir / "examples"
    if not examples_dir.exists():
        return []
    return [p for p in examples_dir.rglob("*") if p.suffix in (".g", ".gi")]


def is_autodoc_tst(tst_path: Path, package_dir: Path) -> bool:
    """Return True if the .tst file was generated by AutoDoc.

    The filename must start with the lowercase package name (e.g. fpcategories01.tst),
    which is the naming convention AutoDoc uses.
    """
    package_name_lower = package_dir.name.lower()
    if not tst_path.stem.startswith(package_name_lower):
        return False
    try:
        with open(tst_path, encoding="utf-8") as f:
            header = f.read(600)
    except OSError:
        return False
    return "DO NOT EDIT THIS FILE" in header or "generated by AutoDoc" in header


def find_source_example(
    tst_path: Path, package_dir: Path
) -> tuple[Path | None, float]:
    """Return the best-matching example file and its similarity score."""
    tst_lines = get_tst_input_lines(tst_path)

    best_score = 0.0
    best_example: Path | None = None

    for eg_path in find_example_files(package_dir):
        eg_lines = get_example_code_lines(eg_path)
        score = similarity(tst_lines, eg_lines)
        if score > best_score:
            best_score = score
            best_example = eg_path

    return best_example, best_score


def write_source_to_tst(tst_path: Path, source_path: Path, package_dir: Path) -> None:
    """Insert/update a 'gap> # extracted from <path>' comment after the doc/ reference line."""
    rel_source = source_path.relative_to(package_dir)
    source_comment = f"gap> # extracted from {rel_source}\n"

    with open(tst_path, encoding="utf-8") as f:
        lines = f.readlines()

    # Remove all existing 'gap> # extracted from' lines anywhere in the file.
    lines = [l for l in lines if not l.startswith("gap> # extracted from ")]

    # Find the '# doc/...' reference line (e.g. '# doc/_Chunks.xml:384-442')
    ref_idx = next(
        (i for i, l in enumerate(lines) if l.startswith("# doc/")),
        None,
    )
    if ref_idx is None:
        return

    # Insert the annotation on the line immediately after the doc/ reference.
    lines.insert(ref_idx + 1, source_comment)

    with open(tst_path, "w", encoding="utf-8") as f:
        f.writelines(lines)


def find_packages(monorepo_root: Path) -> list[Path]:
    """Return package directories that have both tst/ and examples/ subdirs."""
    return sorted(
        d
        for d in monorepo_root.iterdir()
        if d.is_dir()
        and (d / "tst").is_dir()
        and (d / "examples").is_dir()
    )


def main() -> None:
    monorepo_root = Path(__file__).resolve().parent.parent

    # Optional argument: a specific package name or path.
    package_filter: Path | None = None
    if len(sys.argv) >= 2:
        arg = Path(sys.argv[1])
        # Resolve relative to cwd first, then fall back to monorepo_root/<name>.
        cwd_candidate = arg.resolve()
        monorepo_candidate = (monorepo_root / arg).resolve()
        if cwd_candidate.is_dir() and (cwd_candidate / "tst").is_dir():
            package_filter = cwd_candidate
        elif monorepo_candidate.is_dir() and (monorepo_candidate / "tst").is_dir():
            package_filter = monorepo_candidate
        else:
            print(f"Package not found: {sys.argv[1]}", file=sys.stderr)
            sys.exit(1)

    if package_filter is not None:
        packages = [package_filter]
    else:
        packages = find_packages(monorepo_root)

    if not packages:
        print(f"No packages found under {monorepo_root}", file=sys.stderr)
        sys.exit(1)

    # When a single package is targeted, print paths relative to it for brevity.
    single = len(packages) == 1

    unmatched = []

    for package_dir in packages:
        tst_dir = package_dir / "tst"
        if not tst_dir.is_dir():
            continue
        tst_files = sorted(tst_dir.glob("*.tst"))

        for tst_path in tst_files:
            if not is_autodoc_tst(tst_path, package_dir):
                continue

            source, score = find_source_example(tst_path, package_dir)

            rel_tst = (
                tst_path.relative_to(package_dir)
                if single
                else tst_path.relative_to(monorepo_root)
            )

            if source and score > 0.0:
                rel_source = source.relative_to(package_dir)
                print(f"{rel_tst}  <-  {rel_source}  (score: {score:.2f})")
                write_source_to_tst(tst_path, source, package_dir)
            else:
                print(f"WARNING: no match found for {rel_tst}", file=sys.stderr)
                unmatched.append(str(rel_tst))

    if unmatched:
        print(f"\n{len(unmatched)} unmatched test file(s):", file=sys.stderr)
        for f in unmatched:
            print(f"  {f}", file=sys.stderr)


if __name__ == "__main__":
    main()
