name: LinearAlgebraForCAP
version: 2015.10.06
date: 06/10/2015
description: Category of Matrices over a Field for CAP

authors:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche
    - name: Sebastian Posur
      url: http://wwwb.math.rwth-aachen.de/Mitarbeiter/posur.php

maintainers:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche
    - name: Sebastian Posur
      url: http://wwwb.math.rwth-aachen.de/Mitarbeiter/posur.php

GAP: ">= 4.6"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "MatricesForHomalg"
      version: ">= 2015.06.20"
      url: "http://homalg.math.rwth-aachen.de/index.php/core-packages/matricesforhomalg"
    - name: "CAP"
      version: ">= 2015.08.17"
      url: "http://github.com/homalg-project/CAP/"
    - name: "ToolsForHomalg"
      version: ">=2015.09.18"
      url: "http://wwwb.math.rwth-aachen.de/~gutsche/gap_packages/ToolsForHomalg"

www: http://TODO/
readme: http://TODO/README
packageinfo: http://TODO/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://TODO/LinearAlgebraForCAP-2015.10.06.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
