############################################################################
##
##                                ActionsForCAP package
##
##  Copyright 2016, Sebastian Gutsche, University of Siegen
##                  Sebastian Posur,   University of Siegen
##
#! @Chapter Internal Exterior Algebra Modules
##
#############################################################################

####################################
##
## Constructors
##
####################################

##
InstallMethod( InternalExteriorAlgebraModuleCategory,
               [ IsCapCategoryObject ],
               
  function( object )
    local name;
    
    name := Concatenation( "Module category of the internal exterior algebra generated by ", String( object ) );
    
    return LeftActionsCategory( object, name, IsInTheContextOfInternalExteriorAlgebraModuleCategory );
    
end );

##
InstallMethod( InternalExteriorAlgebraModuleCategoryObject,
               [ IsCapCategoryMorphism, IsCapCategoryObject ],
               
  function( structure_morphism, object )
    local result_object;
    
    return InternalExteriorAlgebraModuleCategoryObject( structure_morphism, InternalExteriorAlgebraModuleCategory( object ) );
    
end );

##
InstallMethod( InternalExteriorAlgebraModuleCategoryObject,
               [ IsCapCategoryMorphism, IsCapCategory ],
               
  function( structure_morphism, category )
    
    return LeftActionObject( structure_morphism, category );
    
end );

##
InstallMethod( InternalExteriorAlgebraModuleCategoryMorphism,
               [ IsInternalExteriorAlgebraModuleCategoryObject,
                 IsCapCategoryMorphism,
                 IsInternalExteriorAlgebraModuleCategoryObject ],
                    
    function( source, morphism, range )
      local result_morphism;
      
      return LeftActionMorphism( source, morphism, range );
      
end );

