name: GeneralizedMorphismsForCAP
version: 2015.10.06
date: 06/10/2015
description: Implementations of generalized morphisms for the CAP project

authors:
    - name: Sebastian Posur
      url: http://wwwb.math.rwth-aachen.de/Mitarbeiter/posur.php
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/

maintainers:
    - name: Sebastian Posur
      url: http://wwwb.math.rwth-aachen.de/Mitarbeiter/posur.php
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/

GAP: ">= 4.6"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">=2015.05.08"
      url: "http://github.com/homalg-project/CAP/"

www: 
readme: README
packageinfo: PackageInfo.g

downloads:
    - name: .tar.gz
      url: GeneralizedMorphismsForCAP-2015.10.06.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
